services:
  nginx:
    image: nginx:1.24.0
    container_name: hibit_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
    working_dir: /var/www
    links:
      - php-fpm

  php-fpm:
    image: hibitdev/php-base:8.3.13-fpm
    container_name: hibit_php
    volumes:
      - ./app:/var/www
    working_dir: /var/www
    
