services:
  nginx:
    image: nginx:1.24.0
    container_name: hibit_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www
    working_dir: /var/www
    links:
      - php

  php:
    image: hibitdev/php-base:1.0-fpm
    container_name: hibit_php
    volumes:
      - ./app:/var/www
    working_dir: /var/www
